version: "1"
services: 
  - type: web
    name: Flask Blog
    runtime: python
    buildCommand: pip install -r requirements.txt
    plan: free
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
    - key: PORT
      value: 8000